gradlew :patched:assembleShuangjielong2Dangbei ^
        :patched:assembleShuangjielong3Dangbei ^
        :patched:assembleChaojimaliDangbei ^
        :patched:assembleChaojimali2Dangbei ^
        :patched:assembleChaojimali3Dangbei ^
        :patched:assembleLvsebingtuanDangbei ^
        :patched:assembleShaluomansheDangbei ^
        :patched:assembleChiseyaosaiDangbei ^
        :patched:assembleRenzhemaoDangbei ^
        :patched:assembleRenzhelongjianzhuan2Dangbei ^
        :patched:assembleRenzhelongjianzhuan3Dangbei ^
        :patched:assembleZhadanrenDangbei ^
        :patched:assembleXiaoaojianghuDangbei ^
        :patched:assembleTubageDangbei ^
        :patched:assembleKuaidaxuanfengDangbei ^
        :patched:assembleXiyoujiDangbei ^
        :patched:assembleSanmutongziDangbei ^
        :patched:assembleMaoxiandao2Dangbei ^
        :patched:assembleMaoxiandao3Dangbei ^
