gradlew :patched:assembleShuangjielong2Weijing ^
        :patched:assembleShuangjielong3Weijing ^
        :patched:assembleChaojimaliWeijing ^
        :patched:assembleChaojimali2Weijing ^
        :patched:assembleChaojimali3Weijing ^
        :patched:assembleLvsebingtuanWeijing ^
        :patched:assembleShaluomansheWeijing ^
        :patched:assembleChiseyaosaiWeijing ^
        :patched:assembleRenzhemaoWeijing ^
        :patched:assembleRenzhelongjianzhuan2Weijing ^
        :patched:assembleRenzhelongjianzhuan3Weijing ^
        :patched:assembleZhadanrenWeijing ^
        :patched:assembleXiaoaojianghuWeijing ^
        :patched:assembleTubageWeijing ^
        :patched:assembleKuaidaxuanfengWeijing ^
        :patched:assembleXiyoujiWeijing ^
        :patched:assembleSanmutongziWeijing ^
        :patched:assembleMaoxiandao2Weijing ^
        :patched:assembleMaoxiandao3Weijing ^
