gradlew :patched:assembleShuangjielong2Shafa ^
        :patched:assembleShuangjielong3Shafa ^
        :patched:assembleChaojimaliShafa ^
        :patched:assembleChaojimali2Shafa ^
        :patched:assembleChaojimali3Shafa ^
        :patched:assembleLvsebingtuanShafa ^
        :patched:assembleShaluomansheShafa ^
        :patched:assembleChiseyaosaiShafa ^
        :patched:assembleRenzhemaoShafa ^
        :patched:assembleRenzhelongjianzhuan2Shafa ^
        :patched:assembleRenzhelongjianzhuan3Shafa ^
        :patched:assembleZhadanrenShafa ^
        :patched:assembleXiaoaojianghuShafa ^
        :patched:assembleTubageShafa ^
        :patched:assembleKuaidaxuanfengShafa ^
        :patched:assembleXiyoujiShafa ^
        :patched:assembleSanmutongziShafa ^
        :patched:assembleMaoxiandao2Shafa ^
        :patched:assembleMaoxiandao3Shafa ^
