gradlew :patched:assembleShuangjielong2Aliplay ^
        :patched:assembleShuangjielong3Aliplay ^
        :patched:assembleChaojimaliAliplay ^
        :patched:assembleChaojimali2Aliplay ^
        :patched:assembleChaojimali3Aliplay ^
        :patched:assembleLvsebingtuanAliplay ^
        :patched:assembleShaluomansheAliplay ^
        :patched:assembleChiseyaosaiAliplay ^
        :patched:assembleRenzhemaoAliplay ^
        :patched:assembleRenzhelongjianzhuan2Aliplay ^
        :patched:assembleRenzhelongjianzhuan3Aliplay ^
        :patched:assembleZhadanrenAliplay ^
        :patched:assembleXiaoaojianghuAliplay ^
        :patched:assembleTubageAliplay ^
        :patched:assembleKuaidaxuanfengAliplay ^
        :patched:assembleXiyoujiAliplay ^
        :patched:assembleSanmutongziAliplay ^
        :patched:assembleMaoxiandao2Aliplay ^
        :patched:assembleMaoxiandao3Aliplay ^
